#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/env-generator-lib.sh
source "$SCRIPT_DIR/env-generator-lib.sh"

APP_NAME="docs"
APP_ENV_FILE="$ROOT_DIR/apps/docs/.env.local"

echo "Generating @cms0/docs environment profile"
echo "Output directory: $OUTPUT_DIR"
echo "Press Enter to accept defaults. Optional values can be left empty."
echo

select_profile "$APP_NAME" "$APP_ENV_FILE"

section \
  "1) Docs app runtime" \
  "Configure docs identity, canonical URL, and production analytics gating." \
  "Nextra metadata, static export, and optional Umami analytics."

PORT="$(ask "PORT" "Port" "3008" true)"
ENVIRONMENT="$(ask "ENVIRONMENT" "Runtime environment label" "$ENV_LABEL" true true)"
CMS0_DOCS_PUBLIC_URL="$(ask "CMS0_DOCS_PUBLIC_URL" "Canonical docs URL (optional)" "http://localhost:3008" false)"

section \
  "2) Hosted workspace routing examples" \
  "Configure environment endpoint examples shown in the docs." \
  "Hosted workspace, app integration, and runtime API pages."

CMS0_PUBLIC_APP_URL="$(ask "CMS0_PUBLIC_APP_URL" "Canonical hosted cms0 app URL" "http://localhost:3001" true)"
CMS0_BASE_DOMAIN="$(ask "CMS0_BASE_DOMAIN" "Base domain for env subdomains" "localhost:3001" true)"
CMS0_PUBLIC_ENV_PATH_RUNTIME_ENABLED="$(ask "CMS0_PUBLIC_ENV_PATH_RUNTIME_ENABLED" "Path runtime enabled? (1/0)" "1" true)"
CMS0_PUBLIC_ENV_SUBDOMAIN_RUNTIME_ENABLED="$(ask "CMS0_PUBLIC_ENV_SUBDOMAIN_RUNTIME_ENABLED" "Subdomain runtime enabled? (1/0)" "1" true)"

section \
  "3) Nextra chrome links" \
  "Configure optional repository links in the docs theme." \
  "Navbar project link, edit link, and feedback link behavior."

DOCS_REPOSITORY_BASE="$(ask "DOCS_REPOSITORY_BASE" "Docs repository base URL (optional)" "" false)"
PROJECT_REPOSITORY_LINK="$(ask "PROJECT_REPOSITORY_LINK" "Project repository URL (optional)" "" false)"

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-docs-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Target app: @cms0/docs

PORT=$PORT
ENVIRONMENT=$ENVIRONMENT

# Docs origin
CMS0_DOCS_PUBLIC_URL=$CMS0_DOCS_PUBLIC_URL

# Hosted workspace routing examples
CMS0_PUBLIC_APP_URL=$CMS0_PUBLIC_APP_URL
CMS0_BASE_DOMAIN=$CMS0_BASE_DOMAIN
CMS0_PUBLIC_ENV_PATH_RUNTIME_ENABLED=$CMS0_PUBLIC_ENV_PATH_RUNTIME_ENABLED
CMS0_PUBLIC_ENV_SUBDOMAIN_RUNTIME_ENABLED=$CMS0_PUBLIC_ENV_SUBDOMAIN_RUNTIME_ENABLED

# Nextra chrome
DOCS_REPOSITORY_BASE=$DOCS_REPOSITORY_BASE
PROJECT_REPOSITORY_LINK=$PROJECT_REPOSITORY_LINK
EOF

echo
echo "Generated:"
echo "  $OUTPUT_FILE"
if [ -n "$DEFAULTS_FILE" ]; then
  echo "Defaults source:"
  echo "  $DEFAULTS_FILE"
fi
echo
echo "Next:"
echo "  Review the file, then copy the values you want into apps/docs/.env.local or your deploy provider."
